### ISSUE TITLE
Deleted

### ISSUE THREAD

**Issue by Motschen** [Yoghurt4C/LilTaterReloaded#1]
Nothing was ever here

![tater](https://user-images.githubusercontent.com/49783724/82116501-96c45c00-976a-11ea-9657-1c790d9ef21f.png)

**Comment by Juuxel** [comment]
https://github.com/Yoghurt4C/LilTaterReloaded/blob/92f062a98a0bbb168158a08771aef2ef35eb330d/src/main/java/mods/ltr/mixins/compat/flamingo/FlamingoBlockMixin.java#L30

The injection target `onUse` is not remapped. I believe the fix for this is to have the `remap = false` on the `@At`, not the `@Inject`.

Edit: `remap = false` should also be removed in here to fix another crash that would happen:

https://github.com/Yoghurt4C/LilTaterReloaded/blob/92f062a98a0bbb168158a08771aef2ef35eb330d/src/main/java/mods/ltr/mixins/compat/flamingo/FlamingoBlockEntityRendererMixin.java#L23

**Comment by Yoghurt4C** [comment]
this issue never existed because of https://github.com/Yoghurt4C/LilTaterReloaded/commit/7a84cdc3ea0f4cea74079f7c82508a7e75cb5dc2
you can grab the jar from https://cdn.discordapp.com/attachments/528472643221848085/711219072674824212/LilTaterReloaded-1.0.41.15.2.jar

**Comment by Motschen** [comment]
Still not working for me: https://hastebin.com/hudohajipi.cs

**Comment by Yoghurt4C** [comment]
how the hell? I've literally JUST tested it in prod
![image](https://user-images.githubusercontent.com/11313954/82122165-993eaa00-979a-11ea-8590-c5e170b3abc7.png)

**Comment by Yoghurt4C** [comment]
can you try with https://github.com/Vexatos/Flamingo/releases/download/v1.16/Flamingo-1.15.2-1.16.jar ?

**Comment by Motschen** [comment]
That's the version I was using the whole time.

**Comment by Yoghurt4C** [comment]
your crash log says otherwise `flamingo: Pink Flamingo 1.14-1.13`

**Comment by Motschen** [comment]
But I downloaded the exact same jar you linked, so idk what's causing that.

**Comment by Yoghurt4C** [comment]
can you also try this jar https://cdn.discordapp.com/attachments/528472643221848085/711230707787104266/LilTaterReloaded-1.0.41.15.2.jar ? if you're actually using latest flamingo mod, there's literally no way you should be getting that crash

**Comment by Yoghurt4C** [comment]
![image](https://user-images.githubusercontent.com/11313954/82122915-208e1c80-979f-11ea-814a-419cd952ce2b.png)
:bug:

**Comment by Motschen** [comment]
And even the new jar doesn't work for me for some reason. :(

**Comment by Yoghurt4C** [comment]
just a sec

**Comment by Yoghurt4C** [comment]
I got to the root of the problem, fixing it

**Comment by Yoghurt4C** [comment]
please try https://cdn.discordapp.com/attachments/528472643221848085/711244338633375844/LilTaterReloaded-1.0.51.15.2.jar , turns out I was at fault because I was building against a different version of flamingo

**Comment by Motschen** [comment]
Now it works 👍
